{1}{1}25.000
{1493}{1628}01 Evangelion 1.11 You Are (Not) Alone|- Anime 2007 720p [H264-mp4] English
{1808}{1880}It shows up now, of all times!?
{1880}{1914}Geez...
{2009}{2101}Due to the present state of emergency,
{2101}{2186}all phone lines have been disabled.
{2186}{2211}No good, huh?
{2212}{2263}My cell phone has no signal,
{2263}{2315}and the buses and trains are shut down too.
{2422}{2466}I guess it'll be impossible|to meet her now.
{2498}{2579}I've got no choice. I|should head to a shelter.
{3438}{3493}All missiles have hit the target!
{3969}{4003}Sorry I made you wait!
{4406}{4524}The target is still unharmed. It's|continuing to advance towards Tokyo-3.
{4524}{4581}The Air Force is unable to stop it!
{4590}{4681}Throw everything at it! Have|even the 4th Division open fire!
{4682}{4764}Spare no expense! Destroy|the target at all costs!
{5314}{5374}How the hell?! We made direct hits!!
{5390}{5443}The tank battalion was|completely destroyed.
{5443}{5515}Missiles and artillery are useless...
{5521}{5602}It's pointless! This type of firepower's|not going to get us anywhere!
{5610}{5656}So, it has an AT Field after all?
{5656}{5670}Yes...
{5671}{5742}Conventional weapons are|useless against an Angel.
{5832}{5905}Understood. We'll deploy|it according to plan.
{6017}{6054}No way... it can't be...!
{6054}{6097}They're going to use an N2 Mine?!
{6106}{6138}Get down!
{6617}{6630}We did it!
{6642}{6713}It seems you won't be needed this time.
{6713}{6742}Shockwave incoming!
{6766}{6796}Are you okay?
{6796}{6880}Yeah... but I think I got|some sand in my mouth.
{6880}{6931}Great! Here, help me out...
{6950}{6990}Get ready...
{6990}{7030}And PUSH!
{7230}{7282}Thanks! Couldn't have done it myself.
{7282}{7354}No, I should be thanking|you, Katsuragi-san.
{7366}{7423}Call me Misato, alright?
{7423}{7494}It's nice to meet you, Ikari Shinji-kun.
{7504}{7520}Yeah.
{7530}{7564}What is the target's status?
{7564}{7630}Due to radio interference, the|target cannot be confirmed.
{7568}{7630}With that explosion, it|must be obliterated.
{7638}{7686}Restoring visual.
{7988}{8040}And that was our trump card...
{8074}{8115}How is this possible...
{8115}{8154}Goddamn monster!
{8206}{8269}Thank God my Renault still works!
{8269}{8392}It'd be no joke for this car to die on me, since|I've still got 12 payments left on the lease...
{8392}{8457}Anyway, I called ahead to reserve|an express train for us,
{8458}{8520}so we might still make it in time!
{8524}{8596}Say, don't you have any|questions for me, Shinji-kun?
{8622}{8647}N-no.
{8650}{8706}I've been the only one|talking here, you know!
{8733}{8758}Sorry...
{8760}{8812}Oh, it's nothing to apologize over,
{8812}{8891}but I was sure you were going to|ask "What was that giant thing?,"
{8891}{8943}or maybe, "What's going on here?"
{8944}{8982}you know, those sorts of things?
{8982}{9016}Um, well...
{9031}{9124}I don't see the point, since I didn't|think you'd give me an answer anyway.
{9135}{9198}Wow, you sure jump to wrong|conclusions, don't you?
{9198}{9240}That's something adults do, not teenagers!
{9312}{9342}It's okay.
{9342}{9394}I'm just following my directions.
{9422}{9489}Oh?... never mind then.
{9507}{9591}Just for your information, that thing was a|mysterious life form we call an "Angel."
{9744}{9780}The 4th Angel...
{9790}{9863}It possesses an astounding|regenerative capacity.
{9863}{9947}Complete by itself, it is a|nearly-perfect living creature.
{9948}{9976}Of course it can regenerate.
{9976}{10045}Because Angels partook of the|Fruit of Life, you mean?
{10055}{10166}Yes. They exist to exterminate us... we,|who partook of the Fruit of Wisdom.
{10170}{10253}The gate is closing. Please be careful.
{10292}{10337}"Secret Military Agency NERV"...?
{10337}{10411}Yes, it's a private organization under|the direct control of the U.N..
{10431}{10470}That's where my father is?
{10470}{10499}Well, yeah...
{10499}{10538}Do you know what your dad's job is?
{10648}{10711}"Work of utmost importance in|the protection of humanity."
{10711}{10750}That's what my teacher said.
{10810}{10884}From here on, you will be in|command of this operation.
{10892}{10939}Show us what you can do.
{10939}{10970}Understood.
{10970}{11124}Ikari-kun, I have to admit that nothing in|our arsenal is effective against the target.
{11134}{11181}So you claim you can defeat this thing?
{11203}{11252}NERV exists for that very purpose.
{11283}{11334}Are we going to where my father is?
{11356}{11397}Yeah, I imagine he'll be there.
{11498}{11526}Father...
{11580}{11662}By the way, did your father|send you an ID card?
{11684}{11723}Ah, yeah.
{11760}{11786}Here you go.
{11790}{11815}Thanks.
{11854}{11905}Here, read this please.
{11924}{11954}NERV.
{11976}{12031}My father's work.
{12031}{12080}Is there something I'm needed for?
{12133}{12285}Of course. He wouldn't send me a letter|if he didn't need me for something.
{12286}{12371}I see, you don't get|along with your father.
{12393}{12426}Me neither.
{12559}{12599}Amazing!
{12614}{12661}A real GeoFront!
{12662}{12678}That's right.
{12686}{12767}And that is our secret|base; NERV Headquarters.
{12786}{12887}It's humanity's fortress, the|cornerstone to rebuilding our world.
{12982}{13068}Let's see... from the|terminal's Western exit,
{13068}{13117}Go north to the 3rd gate and take a right.
{13118}{13169}Then, we need to take Route 8...
{13212}{13310}Could they have made this|facility any more complicated?
{13319}{13401}Hmm... this looks like the correct route...
{13401}{13455}Um, are we lost?
{13471}{13509}I'm just not used to this place yet.
{13509}{13584}Either way, if we keep heading|forward we'll eventually get there!
{13597}{13639}Secondary cooling cycle complete.
{13639}{13684}All personnel, evacuate|the tank immediately.
{13690}{13742}I want the left arm's conductive|plating defrosted and ready to go
{13742}{13794}within the next three minutes!
{13795}{13850}And don't forget that apoptosis data!
{13850}{13863}Roger!
{13872}{14041}Attention Professor Akagi: Chief Operations Officer Lt. Colonel|Katsuragi, together with one young boy, have arrived at Shaft S36.
{14047}{14077}What a surprise.
{14091}{14122}She's late yet again.
{14255}{14288}Ah... Ritsuko!
{14312}{14485}You're 12 minutes past schedule. You were taking so long,|I came to greet you personally, Lt. Colonel Katsuragi.
{14485}{14537}We're short on staff and out of time.
{14541}{14566}Eh... Sorry!
{14661}{14709}Is this the boy?
{14710}{14730}Yup.
{14730}{14835}I'm the Chief Engineer and Administrator|of NERV's Project E, Akagi Ritsuko.
{14835}{14861}It's nice to meet you.
{14886}{14905}M-me too.
{14905}{14955}Well then, I'll leave things here to you.
{15065}{15119}It'll be their first meeting in 3 years...
{15119}{15205}Deputy Commander! The|target has begun to move!
{15205}{15231}Understood.
{15231}{15280}All units, Level One battle stations!
{15316}{15400}I repeat, all units, Level|One battle stations!
{15400}{15463}Ground forces, prepare for combat!
{15542}{15632}Ikari Shinij-kun, there's|something I want to show you.
{15722}{15876}The ultimate man-made multipurpose fighting|machine. The artificial human, Evangelion.
{15876}{15902}That is Unit 01.
{15912}{15980}Mankind's very last trump card.
{15980}{16032}This is my father's work?
{16032}{16062}Correct.
{16105}{16133}It's been a while.
{16174}{16205}Father...
{16307}{16332}Prepare to sortie.
{16336}{16372}Sortie?!
{16372}{16433}But Unit 00 is still frozen, isn't it?
{16468}{16524}Unless... You intend to use Unit 01?
{16533}{16567}There is no other choice.
{16613}{16646}Ikari Shinji-kun...?
{16646}{16671}Y-Yes?
{16674}{16700}You will pilot it.
{16844}{16903}Why did you call me here, Father?
{16914}{16975}For the same reason you're thinking.
{16975}{17064}I'm supposed to pilot this and fight|that thing I just saw outside?
{17073}{17094}Correct.
{17094}{17168}I don't want to! What are you|saying all of a sudden?!
{17174}{17242}I thought you didn't need me!|That's why you left!
{17247}{17313}I need you now, so I called for you.
{17364}{17412}Why... me?
{17412}{17471}Because no one else can.
{17483}{17544}I can't do it...
{17544}{17584}I've never seen or heard of this thing.
{17592}{17621}I just can't!
{17625}{17656}We'll explain it to you.
{17665}{17698}No...
{17724}{17778}I can't do it!
{17778}{17823}There's no way I can do this!
{17833}{17905}If you're going to pilot it, do it now.|If not...
{17905}{17932}Leave!
{18202}{18261}So, we've been found...
{18297}{18359}Armored hulls 1 through|8 have been breached!
{18359}{18409}Shinji-kun, there isn't much time.
{18409}{18514}Widespread fire alarms in Block D.|Closing all fire doors in the area.
{18524}{18549}Pilot it!
{18580}{18613}No!
{18613}{18694}Sure, I came all this way...|but this is impossible!
{18724}{18806}Shinji-kun, why did you come here?
{18857}{18954}Don't run away. You have to face your|father... and more importantly, yourself.
{18960}{19080}I know that! But I just can't do this!
{19248}{19274}Fuyutsuki.
{19294}{19342}Wake up Rei.
{19342}{19375}Can we use her?
{19376}{19427}She's not dead.
{19446}{19472}Understood.
{19511}{19536}Rei.
{19536}{19561}Yes.
{19561}{19635}The backup is useless.|We need you once more.
{19635}{19660}Yes.
{19709}{19808}Switch Unit 01's core unit to the|L-00 type and reactivate it!
{19818}{19909}Roger. Suspending current tasks.|Reactivating.
{19909}{19943}Entering reactivation command.
{19943}{20048}I knew it. I was never needed...
{20059}{20107}The Target has broken through|the final defence line,
{20107}{20170}and is proceeding to head right above us.
{21081}{21106}Are you alright?
{21519}{21647}I mustn't run away, I mustn't run away, I|mustn't run away, I mustn't run away...
{21647}{21672}I mustn't run away!
{21700}{21725}I'll do it.
{21732}{21764}I'll pilot it.
{21831}{21874}Third cooling cycle, complete.
{21874}{21913}Flywheel rotation shutdown.
{21917}{21946}Unlocking the connectors.
{21946}{21983}No problems with the auxiliary power.
{21984}{22038}Shutdown signal plug extraction complete.
{22046}{22111}Roger, inserting entry plug.
{22111}{22199}Unlocking spinal conductive network.|Prepare for connection.
{22269}{22311}Probe needle insertion complete.
{22311}{22393}Prime sync established. Psychological|corruption values within acceptable range.
{22394}{22458}Maintaining range between|plus-02 and minus-05.
{22466}{22522}Locking down interior array.
{22522}{22574}Roger, starting first contact.
{22612}{22654}Flooding Entry Plug.
{22691}{22716}W-What is this?
{22780}{22805}It's alright.
{22806}{22914}Once the LCL fills your lungs, it will|provide oxygen directly to your blood.
{22924}{22959}You'll get used to it.
{23003}{23044}Main power source connection complete.
{23044}{23061}Roger.
{23061}{23111}Starting second contact.
{23111}{23142}Initializing interface.
{23202}{23262}A-10 nerve connection is normal.
{23262}{23327}LCL ionization levels normal.
{23327}{23406}Set Japanese as the linguistic|norm for cognitive interface.
{23416}{23478}No problems detected with initial contacts.
{23478}{23531}Communication lines open.
{23547}{23606}Points on the list up to 1405, all clear.
{23614}{23695}Measuring synapse levels.|Synchronization rate, 41.3%.
{23708}{23778}And he's not even wearing a plug suit!|Amazing!
{23778}{23884}Harmonics are in normal levels.|Everything's under control.
{23884}{23909}We are ready!
{23934}{23959}Prepare to launch!
{23970}{23999}Prepare to launch!
{24026}{24067}Release primary lock bolts!
{24111}{24141}Release confirmed.
{24141}{24197}Initiating retraction of umbilical bridge.
{24239}{24278}Release secondary lock bolts!
{24344}{24397}Removing primary restraints.
{24397}{24460}Proceeding to remove secondary restraints.
{24570}{24640}Disengaging safety systems 01 through 15.
{24640}{24676}Disengagement confirmed.
{24681}{24741}Unit 01 is now free.
{24741}{24787}Internal power supply, fully charged.
{24787}{24834}No problems with the external power socket.
{24844}{24919}Understood. Move Unit 01 to the launch pad.
{24925}{24991}No problems with the positioning|of any of the linear rail tracks.
{24991}{25050}Electromagnetic induction|system, working normally.
{25058}{25144}Unit 01 is now moving to K-52.
{25148}{25209}Launch sequence is proceeding normally.
{25214}{25292}Eva has arrived at the launch terminal hub.
{25435}{25483}Launch tube clear. All green!
{25491}{25546}Launch preparations complete.
{25546}{25571}Understood.
{25589}{25625}I have your approval?
{25625}{25655}Absolutely.
{25658}{25738}Our future depends on defeating the Angels.
{25756}{25836}Ikari, you're absolutely sure about this?
{25867}{25892}LAUNCH!
{26490}{26530}Are you alright, Shinji-kun?
{26536}{26561}Y-Yes.
{26564}{26609}Release the final safety lock!
{26638}{26706}Evangelion Unit 01, lift off!
{26786}{26811}Shinji-kun...
{26818}{26882}for now, just concentrate on walking.
{26894}{26922}Walk...
{27123}{27148}It walked!
{27228}{27252}Walk...
{27508}{27553}Shinji-kun, stay alert!
{27553}{27572}Hurry...
{27572}{27618}Hurry and get back up!
{27904}{27942}Shinji-kun, calm down!
{27942}{27993}It's not really your arm that's being hurt!
{28065}{28097}What happened to Eva's defensive systems?
{28098}{28134}Signal inactive!
{28134}{28160}The field isn't expending.
{28161}{28186}It's not working?
{28278}{28309}The left arm is damaged!
{28299}{28327}Circuits are going off-line!
{28392}{28418}Shinji-kun, dodge!!
{28574}{28614}Frontal cranium is fracturing!
{28614}{28652}Its armour can't withstand much more!
{28927}{28967}Cranial damage, severity unknown!
{28971}{29010}Operational integrity compromised!
{29015}{29034}What's the status?
{29039}{29100}Synchro graph inverting!|Pulse entering reflux!
{29108}{29148}Cut off the circuits! Block the flow!
{29148}{29165}We can't!
{29168}{29218}The signal's being refused,|we can't get through!
{29218}{29240}Shinji-kun's status?!
{29240}{29290}No response from the monitoring system.|Condition unknown!
{29293}{29337}Unit 01 has gone silent.
{29340}{29365}Misato!
{29379}{29415}That's it!
{29415}{29479}Abort the operation! Pilot|rescue has top priority!
{29480}{29517}Emergency plug ejection!
{29520}{29575}We can't! It's not responding!
{29578}{29608}What?!
{29796}{29826}The Eva has reactivated!
{29827}{29848}Impossible...
{29848}{29894}It should be knocked out!
{29902}{29927}Has it gone...
{29934}{29959}Berserk?!
{30468}{30493}We've won.
{30644}{30670}An AT-Field?
{30690}{30743}It's pointless. Unless the|AT Field is breached...
{30744}{30783}you can't do anything to an Angel.
{30955}{30989}Left arm restored!
{30989}{31014}Amazing!
{31098}{31152}Unit 01 has also raised an AT-Field!
{31152}{31207}Angel phase space is being neutralized.
{31208}{31261}No. It's corroding it.
{31378}{31445}It broke through that AT-Field|like it was nothing...
{32854}{32880}What is Eva's status?
{33208}{33234}Is this Eva's...
{33250}{33282}True form?
{33474}{33530}Have you decided on a name?
{33530}{33632}If it's a boy, Shinji. If|it's a girl, then Rei.
{33632}{33674}Shinji...
{33674}{33712}Rei...
{33759}{33792}Shinji...
{33811}{33897}Shinji... Ayanami.
{33907}{33945}Shinji...
{33966}{33991}Rei...
{34012}{34088}Rei... Ikari...?
{34097}{34127}Rei...
{34140}{34176}No...
{34191}{34251}Ayanami... Rei!
{34794}{34832}An unfamiliar ceiling...
{35005}{35092}The attack of the fourth|Angel, and its defeat...
{35105}{35175}Then the acquisition of the Third Child...
{35175}{35223}And the activation of Eva Unit 01...
{35238}{35284}Overall the plan is progressing well.
{35290}{35395}Well, except for the colossal expense|necessary to repair Unit 01.
{35395}{35454}Compared to Unit 00 in cryo-suspension,
{35454}{35491}that is hardly a problem.
{35507}{35577}Eva Unit 01's recovery|operation is complete.
{35578}{35643}Right now, it's being locked into Cage 6.
{35644}{35712}A full-systems check will|commence at 10:00 hours.
{35712}{35757}And the recording from|when it went berserk?
{35757}{35841}It was blank. Absolutely|nothing was recorded.
{35841}{35910}And so, we have no idea what the cause was.
{35910}{36012}Our absolute confidence in its combat|performance... may be a bit misplaced.
{36017}{36136}As long as it can fight the 5th|Angel, minor bugs are tolerable.
{36144}{36173}No need for concern.
{36173}{36230}We'll continue deployment of Unit 01.
{36230}{36340}And Unit 02 and its pilot in Germany are|under deployment qualification exams.
{36340}{36419}The construction of Unit 03 is|also progressing as planned.
{36419}{36514}It's your responsibility to make|proper use of NERV and the Evas.
{36514}{36577}We earnestly hope you|will not disappoint us.
{36578}{36693}That's right. Defeating the Angels is but one|step in fulfilling our contract with Lilith.
{36693}{36742}The Human Instrumentality Project...
{36748}{36839}Its execution is our ultimate goal.
{36840}{36952}I understand. Everything will go|according to SEELE's scenario.
{37589}{37694}An Angel leaves quite a mark when it's|destroyed after it loses its AT Field.
{37704}{37756}The blood is like a lake from hell...
{37756}{37843}It's got the same nasty|feeling as the Second Impact.
{37851}{37890}Our Eva can defeat an Angel...
{37897}{37988}That alone will give|humanity a glimmer of hope.
{37993}{38071}Well, looks the pilot of hope just woke up.
{38094}{38183}Paging Chief Internist Dr. Ugai. Dr. Ugai.
{38183}{38298}Please contact Dr. Azuma in the Emergency|Surgical Ward as soon as possible.
{38312}{38399}The B Incident Grand Rounds will|momentarily begin, according to schedule.
{38400}{38506}Would the event directors please make their|way to conference room 2? Thank you.
{39004}{39041}Alone?
{39042}{39166}Yes, he's been assigned quarters|in Block 6. That all right?
{39166}{39196}Yes.
{39196}{39221}Is that really okay?
{39225}{39252}Shinji-kun?
{39253}{39302}It's fine. I'm always alone.
{39321}{39378}It's always the same wherever I go.
{39383}{39401}What?!
{39407}{39528}Like I was saying, I'm taking Shinji|back to my place to live with me.
{39528}{39574}I have authorization from above.
{39574}{39656}Don't worry, I wouldn't lay a|hand on a little boy like him.
{39663}{39756}Of course you won't! Honestly, what are you|thinking?! Don't even say things like this!
{39756}{39809}She could never take a joke...
{39868}{39953}All right, we're gonna|having a party tonight!
{39966}{39990}What for?
{39996}{40076}To welcome my new room-mate, of course!
{40158}{40203}So you've decided to move?
{40203}{40330}Yes, I never thought this city|would become a battlefield.
{40330}{40460}Indeed! My husband wants me and|the children to leave here too!
{40460}{40562}I heard that just today, over|100 people left the city.
{40562}{40717}This may be a fortress city, but those|people at NERV seem rather incompetent.
{40718}{40810}I get chills just thinking|about what happened yesterday.
{40810}{40850}I know...
{40933}{40962}Sorry,
{40968}{41034}but we're going to take a slight detour.
{41034}{41060}Where to?
{41077}{41116}Some place special.
{41272}{41304}This city...
{41316}{41374}seems so lonely, doesn't it?
{41400}{41426}It's time.
{42297}{42322}Amazing...
{42343}{42392}Buildings are sprouting out of the ground!
{42824}{42909}This is the special fortress-city|for intercepting Angels.
{42926}{42966}Tokyo-3.
{42992}{43019}This is our city...
{43082}{43168}And the city that you protected.
{43328}{43408}Looks like your things have|already been delivered.
{43414}{43523}To tell the truth, I've only|moved to this city recently.
{43528}{43564}All right, come on in.
{43594}{43632}Um...
{43638}{43670}Pardon the intrusion.
{43688}{43784}Shinji-kun, this is your home now.
{43942}{43990}I'm... I'm home.
{44006}{44034}Welcome home.
{44094}{44127}Ah yeah...
{44127}{44184}It's a little messy in here,|but try to ignore it.
{44238}{44264}Is this...
{44280}{44305}a little?
{44307}{44384}Oh sorry, could you put the|food in the fridge please?
{44390}{44426}Ah, sure!
{44455}{44480}Ice...
{44496}{44521}Snacks...
{44544}{44578}And nothing but beer?
{44600}{44650}What kind of life does she lead?
{44687}{44729}Let's dig in!
{44729}{44756}Let's eat...
{44976}{45085}Ah, I love it! This is what|makes life worth living!
{45122}{45220}Not hungry? For instant|food, it's pretty good.
{45234}{45327}Well... I'm just not used|to this sort of meal.
{45331}{45397}No! You just can't be so picky!
{45415}{45512}No, that's not it... Um...
{45527}{45554}Isn't this fun...?
{45588}{45636}Having a meal with another person?
{45658}{45698}Uh... yes.
{45716}{45739}All right!
{45739}{45860}Since this is your home now,|feel free to just let loose!
{45874}{45909}Y-Yes...
{45909}{45997}Come on... This "Yes, yes, yes,|yes." is getting on my nerves...
{46004}{46098}You're a boy aren't you?!|Show some backbone, will you!
{46110}{46138}Yes.
{46152}{46179}Well, whatever.
{46186}{46301}Once you'll get in the bath, all those bad|feelings will just wash away in an instant!
{46310}{46354}Bathing lets you wash your life anew.
{46582}{46630}M-M-Misato-san!
{46647}{46672}What?
{46789}{46884}Ah, him? He's my pet bird. They|call them hot spring penguins.
{47102}{47145}Birds like that actually exist?!
{47150}{47257}They used to be a lot more common|15 years ago. His name is Pen-pen.
{47260}{47342}He'll be your other room-mate in this house.
{47368}{47422}Anyway... shouldn't you be covering that?
{47575}{47710}Maybe I'm being overly flamboyant... he|might be able to see right through me.
{47758}{47795}Katsuragi Misato-san...
{47841}{47891}She's not a bad person.
{47891}{47936}Bathing lets you wash your life anew!
{47987}{48057}I tend to remember bad|things when I'm in a bath...
{48100}{48142}How was Rei doing?
{48195}{48268}You went to her hospital|this afternoon, no?
{48292}{48410}There are no problems. Preparing to restart|the frozen Unit 00 is more important.
{48410}{48525}Are you sure about using your son? His|mental state seems to be very unstable.
{48530}{48662}Don't worry about him. His condition will give|us the perfect pretext to reinstate Unit 00.
{48662}{48736}We'll proceed according to Lt. Colonel|Katsuragi's suggestion, then.
{49099}{49216}Even without a preliminary report, they|suddenly selected him as the Third Child.
{49216}{49300}And as if in response, the|Fourth Angel attacks.
{49305}{49405}In addition, Commander Ikari|forces his son to pilot.
{49414}{49484}I certainly feel very|uneasy about that fact...
{49484}{49618}But still, even after successfully defeating|that Angel, I feel surprisingly...
{49633}{49664}unhappy.
{49748}{49793}Another unfamiliar ceiling...
{49822}{49866}No surprise...
{49866}{49948}Nothing about this city is familiar.
{49954}{50000}This is your home now.
{50041}{50084}Why am I even here?
{50452}{50518}Shinji-kun? I'm coming in.
{50598}{50657}I forgot to tell you something.
{50663}{50740}You've done a wonderful|thing worth praising today.
{50754}{50791}You should be proud.
{50796}{50840}Goodnight, Shinji-kun.
{50865}{50892}Hang in there.
{51074}{51177}Sorry, transfer kid. I had to hit ya.
{51177}{51219}To settle the score with you.
{51255}{51383}Real sorry. That guy's little sister was|injured in that big incident the other day.
{51384}{51434}That's just how it is with him.
{51449}{51544}It's not like I piloted|it because I wanted to.
{52041}{52125}How is this something|people would praise me for?
{52126}{52218}Why do I have to get hit just|because I piloted the Eva?
{52350}{52381}Is everything alright, Shinji-kun?
{52381}{52398}Yes.
{52403}{52487}Within each Angel there is a central core.
{52514}{52629}The only way to defeat an Angel|directly is to destroy that core.
{52666}{52753}Therefore, centre on target,|then pull the trigger.
{52844}{52921}This way, you can dispose of them|accurately if you master the process.
{52922}{52947}Okay.
{53083}{53176}Good. Continue practising|like this in induction mode.
{53176}{53201}Okay.
{53356}{53449}Still, I'm quite surprised Shinji-kun|suddenly changed his mind about piloting...
{53449}{53565}That boy only gets through life by silently|obeying whatever people tell him, doesn't he?
{53618}{53700}Center on target, then pull the trigger.
{53708}{53786}Center on target, then pull the trigger.
{53791}{53862}Center on target, then pull the trigger.
{53876}{53932}Center on target, then pull the trigger.
{53997}{54036}Which reminds me...
{54036}{54114}Wasn't Shinji-kun hit by one of|his classmates at his new school?
{54114}{54176}Is our pilot security sufficient?
{54176}{54251}There's no problem with our|intelligence department's surveillance.
{54251}{54299}Besides, it wasn't very bad.
{54299}{54399}It would better if we stayed|out of his private life.
{54399}{54446}Doesn't he live with you?
{54446}{54506}His maintenance is your|responsibility too, you know.
{54512}{54547}That's just it.
{54556}{54627}It's difficult... He's far|more naïve than I expected.
{54633}{54674}Hah, complaining already?
{54674}{54740}You were the one who was so|adamant about taking him in.
{54741}{54777}Quiet, you.
{54895}{55075}You're right, he doesn't have much|of a personality for making friends.
{55094}{55152}Have you heard of the "Hedgehog's dilemma"?
{55152}{55232}Hedgehog? The little spiky things?
{55232}{55338}Hedgehogs have a hard time sharing|warmth with other hedgehogs.
{55344}{55466}The closer they become, the|more they hurt each other.
{55466}{55520}People are like that as well.
{55537}{55577}Like with Shinji-kun right now.
{55577}{55685}The more pain his heart endures,|the more afraid he becomes.
{55810}{55870}Well, eventually he'll realize.
{55892}{56021}Becoming an adult means drawing close|and growing apart over and over...
{56027}{56139}and discovering the way to|avoid wounding one another.
{56155}{56194}I certainly hope so.
{56229}{56351}Anyway, when are we gonna get budget|approval to upgrade Block B here?
{56351}{56433}Eva's maintenance and armaments|are the top priority.
{56433}{56475}Maybe there's no money left?
{56491}{56535}My ass is freezing!
{56786}{56814}An emergency call...
{56820}{56857}I'll go on ahead.
{57219}{57266}We have direct visual of inbound object.
{57266}{57317}E747 has also confirmed the object.
{57317}{57404}Analysis indicates Pattern Blue. There's|no doubt. It's the fifth Angel.
{57414}{57464}All hands, level one battle stations!
{57464}{57536}Roger, ground-to-air missiles ready!.
{57536}{57602}Tokyo-3 entering combat configuration.
{57667}{57714}Retracting central block.
{59036}{59141}Center block and Districts One through|Seven's retraction is complete.
{59146}{59207}All governmental departments|have been notified.
{59207}{59252}Target continuing inbound movement.
{59252}{59330}The anti-air interception|system is 48% activated.
{59337}{59399}Status of non-combatants and civilians?
{59399}{59466}We've already received a|complete evacuation report.
{59484}{59624}All Elementary and Middle School student classes,|please gather in your designated blocks.
{59624}{59752}There is a lost child at shelter|number 323 in Sector Seven.
{59682}{59702}It's happening again.
{59702}{59750}Just text again?
{59766}{59819}They're controlling the broadcast.
{59819}{59878}They won't show us regular|citizens anything.
{59883}{59935}Not even a big event like this!
{60150}{60181}This is a waste of tax money.
{60185}{60276}Some people just aren't happy|unless they burn through some ammo.
{60298}{60372}The Japanese government is demanding|we send out the Evangelion.
{60372}{60456}How annoying. It's not like we weren't|going to do that without their orders.
{60472}{60593}We've started the entry. Ionizing LCL.
{60593}{60672}Father's not even watching me...|Why am I piloting this again?
{60704}{60747}People hate me for this...
{60832}{60916}Hey, I wanna talk to you|about something, alone.
{60916}{60943}What about?
{60943}{60984}Just for a minute, okay?
{60993}{61018}Alright, alright...
{61023}{61056}Right, right, and then-
{61056}{61088}Class Rep!
{61088}{61102}What?
{61102}{61158}We, uh, both need to take a leak!
{61158}{61226}Geez, make it quick!!
{61246}{61282}So, what's this about?
{61282}{61355}I want to see it at least|once before I die!
{61355}{61383}That battle up there?
{61383}{61507}This is the real deal! If I don't go now,|who knows when I'll get another chance...
{61507}{61569}Jeez, Kensuke, what is it with you?
{61569}{61628}"If you waste this moment,|you may waste everything."
{61628}{61726}Come on... Just help me get past the gate.
{61726}{61847}Guess I've got no choice. You're a real|slave to your passions, aren't you?
{61891}{61956}Shinji-kun, are you ready for launch?
{61966}{61992}Yes.
{61992}{62116}Remember. Continuous Gatling gun|fire as you neutralize its AT Field.
{62116}{62170}Just like in practice. You'll be fine.
{62179}{62193}Yes...
{62197}{62222}Launch!
{62586}{62673}Incredible! This was worth the trouble!
{62673}{62713}Yes! This is what I've been waiting for!
{62872}{62897}It's here.
{62959}{63004}- Center on target, then pull the trigger.|- Expanding A.T. Field.
{63005}{63058}Center on target, then pull the trigger.
{63008}{63064}Proceed according to the|plans, okay, Shinji-kun?
{63064}{63090}Yes.
{63284}{63338}Idiot! All that smoke is|obscuring the target!
{63707}{63758}The heck? He's gettin' his ass kicked!
{63758}{63782}He's fine!
{63782}{63813}We're sending up a spare rifle!
{63853}{63878}Grab it!
{63907}{63968}Shinji-kun...? Shinji-kun?!
{63980}{64081}Oh man... Your beating|must have shaken him up.
{64081}{64108}Sh-Shut up!
{64609}{64645}Umbilical Cable has been severed!
{64645}{64694}Eva switching to internal power supply!
{64694}{64763}Operational time remaining|is 4 minutes 53 seconds!
{64891}{64920}It's coming this way!
{65043}{65107}Shinji-kun, are you all right?! Shinji-kun!
{65108}{65132}Damage report?
{65133}{65177}No problems. He's good to go.
{65412}{65459}Shinji-kun's classmates?!
{65459}{65489}What are they doing there?!
{65702}{65755}Why isn't he fighting back?!
{65755}{65836}Maybe he can't move freely...|because we're here!?
{65842}{65929}Unit 01 will reach operational time|limit in 3 minutes 28 seconds!
{65930}{65998}Palm armour overheating. Damage, 58%.
{66099}{66179}Shinji-kun, let those two into the cockpit!
{66190}{66269}Once they're in, get out of there!|We'll start over afterwards.
{66352}{66395}You two, get in, quickly!
{66451}{66492}What the... Is this water?!
{66492}{66524}My camera! My camera!
{66524}{66550}System restarting.
{66663}{66723}Palm surface meltdown has reached|the 3rd protective layer!
{66924}{66961}Now's your chance! Retreat!
{67078}{67148}Use escape route 34. Retreat on|the eastern side of the mountain.
{67148}{67188}Hey, transfer kid, she said "retreat!"
{67191}{67286}I mustn't run away... I mustn't run away...|I mustn't run away...
{67205}{67230}Transfer kid!
{67378}{67412}Progressive Knife equipped!
{67465}{67536}Shinji-kun, listen to my order!|Fall back now!
{67542}{67568}Shinji-kun!
{67698}{67722}That idiot!
{68204}{68276}Unit 01 will reach operational|time limit in 30 seconds.
{68288}{68364}28, 27, 26...
{68364}{68458}25, 24, 23, 22...
{68549}{68645}13, 12, 11, 10...
{68648}{68761}9, 8, 7, 6, 5...
{68770}{68864}4, 3, 2, 1...
{69087}{69142}Eva Unit 01 has ceased operation.
{69142}{69213}Target has completely disintegrated.
{70196}{70246}Why did you ignore my orders?
{70267}{70296}I'm sorry.
{70307}{70366}I am your operational supervisor, am I not?
{70382}{70406}Yes.
{70407}{70480}It's your duty to follow|the orders I give you.
{70485}{70512}Do you understand?
{70527}{70552}Yes.
{70555}{70602}Make sure this doesn't happen again.
{70625}{70650}Yes.
{70667}{70716}Do you really understand|what I'm telling you?
{70726}{70798}Yes, I understand, Misato-san.
{70828}{70881}It's fine, we won, didn't we?
{70908}{70980}I'll pilot it if you tell me to.|Isn't that what you want?
{71310}{71394}That's enough. Go back and get some rest.
{71985}{72062}Next stop is Nagao Pass. Nagao Pass.
{72070}{72118}Please exit to the right.
{73232}{73283}He doesn't plan on coming home...
{73284}{73308}That idiot.
{74550}{74601}Ikari, Ikari Shinji.
{74618}{74704}What's this? He just got here,|and he's already absent?
{74704}{74806}Oh well. Now then, I'll hand back|the tests from the other day.
{75812}{75848}I've had enough of this!
{75883}{75952}Please take me back to Misato-san!
{76468}{76575}Did your little stroll clear things|up for you, Ikari Shinji-kun?
{76672}{76774}Not really. It didn't really matter.|Nothing does.
{76792}{76848}I don't have any freedom anyway.
{76894}{76977}I have no choice but to pilot Eva, do I?
{76977}{77036}That's the only reason my father|called for me, after all.
{77067}{77127}Fine. I'll pilot it.
{77127}{77202}If that's what everyone|wants, that's what I'll do.
{77213}{77286}You talk about everyone else,|but what about yourself?
{77286}{77422}I know I can't do this. I bet|everybody else does, too.
{77422}{77499}But Ayanami is hurt, and|you and father want...
{77500}{77532}Cut it out!
{77532}{77590}This has nothing to do with anyone else!
{77590}{77698}You need to decide if you want|to be the pilot for the Eva.
{77698}{77747}You're free to go if you want to.
{77748}{77831}You have all the freedom you want.|Do as you please!
{77958}{78065}In the end, your son's actions|followed the plan to the letter.
{78076}{78164}Yes. Next we must make|him and Rei get closer.
{78180}{78227}All is according to plan.
{78250}{78306}A scenario written out 14 years ago.
{78306}{78386}These poor children's fates|have already been determined.
{78411}{78448}Don't you find that a bit harsh?
{78615}{78685}C'mon, hurry it up! And don't hold back!
{78697}{78763}If you don't do this, I won't|feel like it's settled!
{78763}{78852}Well, that's just the kind of straightforward|guy he is. I'm counting on you.
{79027}{79120}Now we're even. I'm sorry|for hitting you, Ikari.
{79461}{79491}Go, go, Kayoko!
{79510}{79553}If you lose, you're buying us a pizza!
{79553}{79582}That's it! Go, go, go!
{79582}{79602}In your dreams!!
{79602}{79656}Please! Give me one more chance!!
{79656}{79702}Ew, the boys are peeping!
{79702}{79719}Pervs!
{79719}{79747}That's naughty!
{79747}{79794}Suzuhara's gaze is so lewd!
{79796}{79842}Ikari-kun~!
{79910}{79949}Ayanami Rei, age 14.
{79970}{80078}She was the first candidate|chosen by the Marduk Institute.
{80078}{80116}The First Child.
{80116}{80232}Specifically, she is the exclusive operator|of the prototype Evangelion, Unit 00.
{80232}{80329}Her personal history is blank.|Completely erased.
{80330}{80416}So, to save her, my father...
{80427}{80475}Critical error in start-up system!
{80475}{80518}Failures in Stage 3 routines!
{80518}{80577}Nervous system elements rejected.
{80577}{80622}The main transmission system is scrambled!|It's overflowing!
{80627}{80688}Neural pulse flow reversing!|I'm unable to stop it!
{80691}{80742}Direct camera feed, down!
{80745}{80816}Entry plug unstable. Eva|is refusing to release it!
{80819}{80897}Abort contacts. Close off all|circuits up to number six.
{80905}{80964}I can't! The signal won't go through!
{80999}{81040}Unit 00 is out of control!
{81043}{81097}Abort the test. Cut all power.
{81097}{81122}Yes, sir!
{81271}{81324}Unit 00 has switched to auxiliary power.
{81324}{81384}35 seconds to total system shutdown.
{81384}{81432}Fail-safe system has yet to activate.
{81596}{81630}It's dangerous! Please step back!
{81686}{81730}The auto-eject has activated!
{81734}{81759}Oh no!
{81883}{81918}We still cannot control Unit 00!
{81918}{81956}Quickly, release specialized Bakelite!
{81995}{82020}Rei!
{82100}{82172}Ten seconds to complete shutdown!
{82172}{82272}8, 7, 6, 5...
{82272}{82362}4, 3, 2, 1.
{82426}{82470}Unit 00 has ceased all activity.
{82818}{82868}Rei, are you alright?
{82888}{82912}Rei!
{83030}{83055}That's good.
{83196}{83251}It was so sudden. I couldn't believe it.
{83252}{83351}It was deleted from the official|report, but it's an undisputed fact.
{83361}{83451}Unit 00 just went berserk,|and is still being unfrozen.
{83452}{83489}Isn't that a bit hasty?
{83489}{83600}The Angels have reappeared. It's our top|priority to reinforce our military strength.
{83610}{83665}That's true, but...
{83668}{83742}We've already run|reactivation tests with Rei.
{83742}{83790}Unit 00 itself is ready.
{83825}{83890}Once the adjustments to the|nerve connections are complete.
{83891}{83962}It's so we can re-deploy it soon, isn't it?
{84083}{84119}Ayanami...
{84119}{84182}Why is she always alone?
{84182}{84246}Eva Unit 01 is beginning|third coolant phase.
{84254}{84348}Please set all systems in|Cage 6 to phase three.
{84359}{84494}Copying the all-range data of the|entry plug to Melchior. Data sent.
{84539}{84588}Begin third cooling phase.
{84588}{84648}Copying situation data|from Casper to Melchior.
{84648}{84770}Currently, Unit 01's plug depth is at 0,8.|It's within acceptable measurement range.
{84796}{84892}T-minus 150 minutes to Unit 00's|conductive systems restart and testing.
{84896}{85007}Roger. Routine synchronization|test, Program 508 is now complete.
{85007}{85044}Good work, Shinji-kun.
{85105}{85166}So, what's it like living with him?
{85166}{85208}It's alright. I'm getting used to it.
{85211}{85250}Still a little nervous?
{85254}{85330}It's not your first time|living with a man, is it?
{85361}{85418}This isn't like 8 years ago.
{85418}{85468}This time, it's not an|intimate relationship.
{85468}{85499}I don't know about that...
{85511}{85591}Shinji-kun is still here|because of you, isn't he?
{85591}{85628}You're wrong there.
{85644}{85698}It's probably because his father's here.
{85746}{85837}He wants his father to acknowledge him.|To pat him on the shoulder.
{85837}{85902}To praise him, even if it's just one word.
{85917}{85994}I think he wants a love that|will wipe away his loneliness.
{86032}{86122}He's conflicted over his father,|just like you are, Misato.
{86174}{86287}I wonder why Commander Ikari acts|so distant with his own son.
{86287}{86337}And it looks like he talks to Rei a lot.
{86338}{86372}It's a terrible balance.
{86375}{86472}Lately, it seems like men have no interest|in anything other than themselves.
{86482}{86550}It's a tough time to be a woman, isn't it?
{86592}{86623}Well, then...
{86656}{86717}It's about time. I have to head back.
{86717}{86787}You're a worker bee, as always.
{86788}{86906}Take these if you're going home, Misato.|It's Shinji-kun's official security card,
{86906}{86954}and Ayanami Rei's renewed card.
{86954}{87008}I forgot about these.
{87008}{87053}Could you ask Shinji to give this to her?
{87116}{87145}Alright.
{87218}{87244}Ayanami Rei...
{87383}{87436}Why was father smiling with her...?
{87476}{87523}Why won't he smile for me?
{88270}{88327}Excuse me...
{88408}{88472}Excuse me, it's Ikari!
{88520}{88560}Ayanami, I'm coming in.
{89466}{89494}Could these be Ayanami's?
{89853}{89890}Oh, no... Um... I...!
{89966}{89998}I didn't mean to...
{90828}{90853}Could you move?
{90943}{90989}U-um...!
{91430}{91455}What is it?
{91482}{91543}Um... I was... Um...
{91552}{91577}That is...
{91682}{91773}I... I was asked to... I mean...
{91795}{91828}The uhhh...
{91828}{91947}The card! The c-card was renewed and...|and I c-came to deliver it...
{92006}{92103}So... So... It's not|like I was trying to...
{92269}{92376}Ritsuko-san said she forgot|to give it to you. Honestly.
{92376}{92498}I rang the doorbell, but no one answered...|and the door was unlocked, so...
{92800}{92868}Offices in the Central Dogma|are currently accessible.
{92875}{92957}Group 3 visitors are requested|to please use Direct Gate 4.
{93055}{93156}Here's your new card, Ayanami.|Ritsuko-san left it with me.
{93353}{93403}Sorry about before.
{93403}{93428}What for?
{93542}{93616}Say, Ayanami... Aren't you afraid?
{93626}{93694}About piloting that Evangelion again.
{93716}{93743}Why should I be?
{93772}{93857}I heard you got hurt in that test...
{93857}{93934}So... Are you really okay?
{93983}{94038}Yes. I'm okay.
{94048}{94151}But... aren't you afraid|it will go berserk again?
{94161}{94261}Or we could lose to an Angel and die!
{94293}{94349}You're Commander Ikari's son, aren't you?
{94396}{94468}You don't have faith in your father's work?
{94481}{94543}Of course not! Not from a father like him.
{94640}{94664}Um...
{95209}{95279}Monitored object is proceeding|past the Odawara defence Line.
{95280}{95331}Object analysis complete.
{95334}{95383}Pattern blue. Angel confirmed.
{95392}{95448}As we thought. The 6th Angel.
{95458}{95485}Yes.
{95500}{95546}Prepare Unit 01 for sortie.
{95560}{95624}Prepare to launch Unit 01!
{95628}{95672}Anti-air interception weapons armed.
{95737}{95795}The target is passing above Lake Ashinoko.
{95795}{95843}Evangelion Unit 01 is ready to launch!
{95846}{95870}Launch!
{96096}{96147}High energy reaction|detected inside the target!
{96148}{96163}What?!
{96166}{96190}Don't tell me...!
{96260}{96285}Get out of there!
{96770}{96811}Lower synchronization rate to minimum!
{96812}{96841}Deploy blast shield!
{97400}{97467}Abort intercept! Begin|emergency recovery of Unit 01!
{97468}{97532}We can't! The catapult has melted.|It's unusable!
{97535}{97562}What about the AT-Field?
{97562}{97649}Fully raised. Structural integrity|is holding, but barely!
{97785}{97836}No! No more of this!
{97836}{97912}Let me out! Get me out of here, father!!
{97914}{97943}Abort the operation!
{97943}{98019}Place top priority on the pilot's safety!|Force eject the plug!
{98020}{98045}That won't do.
{98082}{98195}If the pilot is taken out, Eva's|AT-Field will completely disappear!
{98209}{98260}Things will go from bad to worse.
{98284}{98309}But...
{98480}{98508}There's no other choice...
{98545}{98618}Emergency recovery! Blow|the explosive bolts!
{99168}{99212}The target has ceased fire.
{99212}{99269}Unit 01 retrieved. Sending to Cage 99!
{99269}{99295}Rescue team, stand by!
{99298}{99353}First priority is cooling|the LCL in the plug!
{99358}{99403}Pilot confirmed! His heart rate is weak.
{99405}{99484}Boost plug suit life support to Max!|Begin cardiac massage!
{99484}{99509}Understood!
{99570}{99601}Pulse confirmed!
{99606}{99635}Forcefully eject the plug!
{99678}{99733}Stabilizing possible rupture|point in the interior.
{99736}{99775}Begin emergency LCL draining!
{99775}{99800}At once!
{99808}{99847}Draining LCL.
{99850}{99876}Hurry emergency treatment!
{100850}{100914}The target is currently|invading from above.
{100922}{100973}It's in the midst of drilling|through to the Geo-Front.
{100973}{101072}Its objective is a direct|attack on our NERV HQ, is it?
{101084}{101154}Well then, let's hear the results|of each department's analysis.
{101173}{101212}Judging from the previous battle...
{101212}{101324}the target automatically engages|any enemy within a certain range.
{101326}{101404}Meaning it's impossible for Eva to|engage it in close combat, right?
{101404}{101437}How's its AT Field?
{101445}{101493}Still operational. And|to make matters worse...
{101494}{101581}with its phase pattern constantly shifting,|the field's surface is unstable.
{101582}{101634}Neutralizing it will be very difficult.
{101645}{101684}According to Magi's calculations...
{101687}{101887}to pierce the enemy's AT Field, we'd need to drop so many|aerial N2 Mines that it would destroy NERV HQ as well.
{101914}{101988}The Magi 2 at Matsushiro|reached the same conclusion.
{102002}{102148}Right now, the Japanese government and U.N.|Forces are petitioning NERV HQ to do just that.
{102148}{102215}An easy suggestion to make when|they're not the ones in danger.
{102226}{102286}If this place falls, then all is lost.
{102286}{102398}However, the drill has already breached|the second layer of armour plating.
{102404}{102466}It's already begun penetrating the third.
{102466}{102572}The estimated time from today until|it has passed through all 22 layers,
{102572}{102707}reaching the area above HQ, is|12:06:54 AM tomorrow morning.
{102710}{102764}We have ten hours and fourteen minutes.
{102767}{102848}To make matters worse, Unit 00 needs to|be calibrated before it's operational.
{102848}{102947}Unit 01 is also currently unmovable|due to its previous injury.
{102976}{103041}The situation sure isn't favourable.
{103041}{103103}We're certainly backed into a corner.
{103103}{103157}Should we wave the white flag?
{103169}{103293}Maybe... but before we do, I have a|little something I'd like to try.
{103309}{103397}The intelligence division should be aware|of the JSSDF's secret weapon, right?
{103772}{103910}Still, though, it's reckless to use this in|an operation, Operations Chief Katsuragi.
{103919}{103958}"Reckless" is a bit rude.
{103968}{104071}It can be done within the remaining nine|hours, and it's the best shot we've got.
{104076}{104114}Operation Yashima...
{104124}{104227}As the name suggests, we'll be taking|electrical power from all over Japan.
{104227}{104387}And then direct it toward JSSDF's secret|prototype weapon, a high power positron cannon.
{104440}{104588}Since it's unfinished, and can't be used on its|own, it's been modified for Eva to control it.
{104613}{104757}Convincing the U.N. Forces is one thing, but|the Ministry of Home Affairs and JSSDF, too?
{104774}{104850}Let's just say they owe me a few favours.
{104931}{104979}You sure are good at what you do.
{105019}{105166}From midnight tonight to before dawn tomorrow, the|entire country will experience a large-scale blackout.
{105169}{105273}We ask for everyone's cooperation.|I repeat...
{105278}{105433}From midnight tonight to before dawn tomorrow, the|entire country will experience a large-scale blackout.
{105433}{105507}We ask for everyone's cooperation.
{105441}{105487}Alright. Let's go.
{105494}{105507}Yeah.
{105507}{105682}From midnight tonight to before dawn tomorrow, the|entire country will experience a large-scale blackout.
{105682}{105756}We ask for everyone's cooperation.
{106302}{106357}The Angel has penetrated|through the 7th armoured plate!
{106360}{106400}What's the status of our energy system?
{106403}{106528}Power will be fed directly from the Shingotenba|substation and two backup generators!
{106528}{106646}Superconductor power lines now being|laid towards lower Futagoyama.
{106646}{106786}The transformer relay system is scheduled to|be up and running at 10:50 PM Japan time.
{106789}{106834}How's progress on the sniping system?
{106841}{106938}No problems in assembly. We'll have no trouble|making it by the operation start time.
{106941}{106980}What is Unit 01's status?
{106986}{107064}It's currently being outfitted|with G-type sniping equipment.
{107073}{107118}It will be ready to deploy in two hours.
{107123}{107188}Roger that! All that's|left now is the pilot.
{107221}{107284}But I wonder... Will he be|willing to pilot it again?
{107358}{107435}What do you plan to do|about Unit 01's pilot?
{107446}{107518}It's too soon to test|the dummy plug system.
{107534}{107635}We have no other practical means other|than letting the current pilot handle it.
{107635}{107691}In the worst case, do we brainwash him?
{107691}{107757}If things don't work|out, there's always Rei.
{107769}{107875}Rei in Unit 01? Isn't that a bit too risky?
{107894}{108029}We must use whatever means are available to us.|We still have eight Angels we must defeat.
{108068}{108122}And then, we realize our goal...
{108347}{108406}I hate it... piloting the Eva.
{108449}{108542}If I do it well, no one|praises me for doing it.
{108543}{108631}If I fail, everyone will hate me.|Or, even worse, I could just die.
{108659}{108700}Why am I even here?
{108758}{108881}I thought things would change here.|That maybe good things would happen.
{108884}{108937}I didn't come here to be put through hell.
{108940}{109043}So you plan to spend the rest of your life|running away from everything unpleasant?
{109083}{109114}Live?
{109130}{109168}Why am I alive, anyway?
{109196}{109258}I used to think I didn't|have a choice in the matter.
{109302}{109397}Whether it's my father or|Misato-san, no one really needs me.
{109397}{109459}If I couldn't pilot Eva, there|would be no need for me.
{109490}{109549}That's why I have no|choice but to pilot Eva.
{109578}{109632}That's why I'm able to stay here.
{109650}{109719}But when I pilot my Eva, I...
{109826}{109875}This ceiling again...
{109919}{109976}Is this all I get for piloting that thing?
{110081}{110112}Ayanami...?
{110160}{110188}You were here the whole time?
{110244}{110381}I'm here to tell you about the schedule for Operation|Yashima, which will commence at midnight tomorrow.
{110381}{110535}Pilots Ikari and Ayanami are to|report at Terminal 2 at 19:30.
{110535}{110661}At 20:00, Unit 01, accompanied|by Unit 00, will be transferred.
{110661}{110718}Launch is scheduled at 20:05.
{110718}{110793}By 20:30, they will arrive at|the 2nd Futagoyama fortress.
{110806}{110876}After that, they will await further orders.
{110876}{110975}When the clock strikes midnight,|the operation will begin.
{111009}{111034}Your food.
{111082}{111126}I don't feel like eating anything.
{111138}{111189}We leave in 90 minutes.
{111202}{111270}You're saying I'll be|piloting that thing again?
{111270}{111290}Yes.
{111290}{111403}I don't want to. I don't want|to feel that scared anymore.
{111403}{111513}It's terrifying...! But I|can't even run away...
{111513}{111556}You're afraid of Eva?
{111578}{111619}Then stay and rest.
{111657}{111685}Rest?
{111694}{111747}I will pilot Unit 01.
{111814}{111839}Ayanami!
{111861}{111886}Farewell.
{112298}{112358}The Angel is penetrating through|the 17th armoured plate!
{112358}{112430}Target will reach NERV Headquarters|in 4 minutes 55 seconds.
{112430}{112543}The new western Hakone line and the southern|Tounosawa overhead line have been electrified.
{112543}{112656}Currently, the number 16 substation is continuing|to establish its transformer equipment.
{112656}{112787}500,000 volts are flowing through the transformers|as planned. No changes to the time sheet.
{112800}{112882}The 28th transformer group will|arrive after a five minute delay.
{112882}{112960}All related persons, please|hurry to your respective lines.
{112968}{113094}Begin proceeding to Stage Four of the simulation.|Now re-checking recovery and support systems.
{113106}{113256}All SMES have been set up. Sequential|start-up from the first bundle confirmed.
{113262}{113390}All mega-high voltage superconductor transformers'|opening and closing checks complete. No problems.
{113613}{113671}So this is the giant positron cannon?
{113681}{113774}The assembly was rushed, but|theoretically it should work.
{113774}{113878}We're zeroing the alignment on our end and getting|it ready to link with the G-type equipment.
{113878}{113931}And, well, the rest is up to you.
{113944}{114002}You mean up to the pilot.
{114022}{114082}Misato, I sure hope this works.
{114202}{114296}Shinji-kun, you were|supposed to report long ago.
{114366}{114450}You chose to stay here, didn't you?
{114466}{114528}Then do your job properly.
{114570}{114643}I'm afraid of piloting the Eva...
{114668}{114716}You and the others have|nothing to be afraid of.
{114734}{114827}You're always just giving orders|from your base underground.
{114827}{114890}I'm the only one experiencing|these terrifying things.
{114902}{114942}You all are hypocrites.
{115150}{115186}Come with me for a sec.
{115381}{115406}Fifteen years ago,
{115431}{115514}half of humanity died in the Second Impact.
{115541}{115614}If the Angels cause a Third Impact now,
{115614}{115695}humanity will die out. No one will survive.
{115716}{115772}I've heard this story|countless times already.
{115873}{115998}If an Angel ever reaches Level|EEE of NERV Headquarters...
{116027}{116095}an automatic self-destruct would commence.
{116136}{116264}We will sacrifice ourselves to prevent|the Third Impact from happening.
{116264}{116366}Everyone who works here understands|and accepts that risk.
{116826}{116851}This is...
{116912}{116972}It can't be... An Eva...!?
{116984}{117133}Not quite. The bringer of life to this|planet, and the agent of its extinction...
{117133}{117216}The Second Angel, Lilith.
{117216}{117245}Lilith...?
{117251}{117341}Yes. Some believe it will act as|the trigger for the Third Impact.
{117370}{117463}We fight with the Evas to protect Lilith.
{117464}{117518}That is something that only you can do.
{117532}{117641}We're entrusting the future of|humanity to you and the Eva.
{117664}{117751}And why give me that|painful responsibility?
{117764}{117871}No reason. Fate chose you, that's all.
{117891}{118018}But you're not the only one putting|your life on the line here, Shinji-kun.
{118032}{118065}We all are.
{118186}{118255}I'll pilot it... one more time...
{118623}{118717}I will now inform you of your|roles in this operation.
{118717}{118742}Shinji-kun.
{118742}{118761}Yes?
{118761}{118815}You will act as gunner in Unit 01.
{118816}{118840}Yes.
{118841}{118899}Rei, you and Unit 00 will be on defence.
{118912}{118937}Yes.
{118944}{119028}The operation this time|calls for utmost precision.
{119040}{119191}That's why, instead of the uncalibrated Unit 00, we chose|to use Unit 01, even though it's still undergoing repairs.
{119205}{119241}Listen, Shinji-kun.
{119241}{119392}Because of the Earth's rotation, magnetic field, and|gravity, the positron cannon won't fire straight.
{119392}{119453}Don't forget to take those|factors into account.
{119466}{119536}You must strike the core in a single shot.
{119546}{119604}But I don't know where this one's core is.
{119614}{119739}Don't worry. There's a portion that|materializes during its attack phase.
{119756}{119820}We believe that's where|its core is located.
{119820}{119956}Your sniping position, as well as various factors that|affect your trajectory, will all be in putted by us.
{119956}{120102}Thus, all you have to do is to follow the on-screen|prompts, and fire when the center indicators meet.
{120114}{120159}The machine will handle the rest.
{120212}{120350}However only one spot has been set|up to supply all of this power.
{120364}{120443}For that reason, Unit 01 cannot|change its firing position.
{120460}{120510}Retreating isn't an option, then?
{120510}{120535}Correct.
{120537}{120615}So what if I miss, and|the Angel shoots back?
{120615}{120741}Don't concern yourself with unnecessary thoughts|now. Focus on destroying the target in one shot.
{120759}{120822}If I don't, we'll be in a big pinch, huh?
{120834}{120930}I... I am supposed to protect Unit 01?
{120930}{120955}Yes.
{120957}{120982}Understood.
{120998}{121053}It's time. Both of you, get dressed.
{121066}{121091}Yes.|Yes.
{121300}{121331}You know...
{121393}{121460}we might die this time.
{121520}{121545}No.
{121577}{121623}You won't die.
{121642}{121677}I will protect you.
{121832}{121897}I'm not worth protecting...
{121927}{121984}This message was left at|NERV Public Affairs Dept.
{122193}{122247}Um... This is Suzuhara.
{122266}{122365}Ikari... No, let me call you Shinji.
{122366}{122410}Shinji, we're counting on you!
{122460}{122511}Hey, this is Aida.
{122511}{122572}Ikari, do your best!
{123687}{123756}Ayanami, why do you pilot your Eva?
{123819}{123845}Because of my bond.
{123866}{123900}Your bond?
{123911}{123963}Yes. My bond.
{124007}{124041}With my father?
{124066}{124098}With everyone.
{124123}{124188}You're strong, Ayanami.
{124226}{124287}I don't have anything else.
{124330}{124390}It's time. Let's go.
{124488}{124512}Farewell.
{124718}{124860}Be aware that, as of now, it|has just passed midnight.
{124970}{124996}It's time.
{124996}{125128}Shinji-kun, you chose to pilot your Eva.|If only for that, I am grateful.
{125134}{125159}Thank you.
{125175}{125218}Begin Operation Yashima!
{125219}{125259}Begin cannon pre-fire sequence.
{125262}{125302}Initiate Stage One power connect.
{125307}{125406}Roger. Switching circuits in|primary and secondary substations.
{125406}{125461}Deploy all switchers. Begin power connect.
{125496}{125602}All power stations holding at maximum.|0.7 to maximum power threshold.
{125607}{125653}No problems in the power supply system.
{125658}{125735}Increasing frequency modulation|capacity to 6.5 million watts.
{125735}{125781}No irregularities in any of the inverters.
{125781}{125849}Stage One circuit breaker|system is operating optimally.
{125849}{125924}All districts from 1 through 803's|power supply circuits are open!
{125928}{126010}Voltage stable. System|frequency maintaining at 50hz.
{126021}{126054}Initiate Stage Two power connect.
{126090}{126133}Shingotenba transformer, valve open!
{126133}{126171}Shinsusouno transformer, valve open!
{126171}{126235}Following that, the Shinyugawara extra|transformer will open its valve.
{126239}{126284}Voltage modulation within safety range.
{126291}{126328}Initiate Stage Three power connect.
{126328}{126403}Roger. Routing all power|to Futagoyama transformer.
{126406}{126472}Maintain maximum allowable|power transmission strength.
{126476}{126534}All cooling systems|running at full capacity.
{126534}{126615}The superconductor energy storage|groups are 78.6 percent charged.
{126615}{126666}Indicator confirms no irregularities.
{126631}{126660}Flywheel, beginning rotation.
{126660}{126736}Keeping the largest possible amount of|energy converted from western Japan.
{126745}{126790}No problems detected with third connection.
{126799}{126864}Understood. Inform barricades 4 and 5
{126872}{126916}to proceed according to plan.
{126916}{126969}Pull back observation aircraft.
{127706}{127758}No. 3 ground-to-ground system, vaporized!
{127758}{127820}All according to plan. Don't|pause for even a second! Next!!
{128125}{128154}No. 2 Turret Battery has been hit.
{128155}{128204}The eighth VLS group has been vaporized!
{128204}{128261}No. 4 ground-to-ground defence|system, initiating attack.
{128296}{128352}No. 6 Missile Battery, obliterated.
{128382}{128440}Commencing third wave of laser attack.
{128448}{128505}Next, No. 7 Turret Battery will open fire.
{128509}{128579}Positron cannon charging.|Currently at one terawatt.
{128586}{128650}Maintain condenser fans at 38000 RPM.
{128650}{128703}Compression density|approaching firing threshold.
{128703}{128744}Increasing power feed.
{128744}{128796}Voltage conversion rate|is at 0.019 percent.
{128803}{128858}Shut down overloaded circuit!|Expedite reroute!
{128858}{128902}Power drop off is within acceptable range.
{128912}{128974}Circuit breakers are operational.|Recovery in progress.
{128978}{129027}No problems with the fourth connection.
{129030}{129073}Disable final safety device.
{129076}{129101}Raise firing hammer!
{129251}{129313}Initiating final input|of sniping parameters.
{129324}{129435}Adjusting for Earth's rotation and gravity.|Plus 0.0009.
{129435}{129496}Firing mechanism is|automatically locking on.
{129510}{129558}Scope adjustment complete.
{129558}{129664}The photons are accelerating.|0.2 to discharge... 0.1...
{129667}{129712}Open the fifth and final connection!
{129742}{129808}Route all energy to power|discharge subsystem.
{129808}{129880}Plugs 1 through 9, ready for power influx.
{129883}{129975}Proceeding with final calibration of|positron acceleration chamber. No problems.
{129975}{130028}I'm not prepared for this like Ayanami is.
{130048}{130117}And I don't have the|confidence to handle my Eva.
{130138}{130204}I just do what I'm told,|without any reason.
{130223}{130268}Protect humanity...?
{130284}{130371}I didn't even realize I was|doing such a vital thing...
{130371}{130408}So why does it have to be me?
{130457}{130529}13, 12, 11...
{130529}{130629}10, 9, 8, 7...
{130631}{130780}6, 5, 4, 3, 2, 1.
{130783}{130808}Fire!
{131312}{131336}Did we get it?!
{131505}{131526}It missed?!
{131526}{131561}Impossible! Was it the timing?!
{131588}{131631}High-order energy reading|detected from target!
{131634}{131674}All hands, brace for impact!
{132518}{132558}What's the status of the energy system?
{132560}{132644}It's still usable. We're|already recharging!
{132644}{132680}And the positron cannon?
{132680}{132753}Still operational. Barrel|cooling now in progress.
{132754}{132821}But unable to verify if|another shot is possible.
{132821}{132883}No need to verify. Just do it.
{132883}{132913}Shinji-kun, are you alright?!
{132938}{133015}Hurry and get Unit 01 back|into firing position!
{133067}{133092}Shinji-kun?!
{133337}{133414}Unit 01's pilot is hereby relieved of duty.
{133425}{133495}We'll entrust the task of|sniping to Unit 00's pilot.
{133503}{133528}Ikari!
{133536}{133608}If he is of no use, we have|no choice but to cut him off.
{133608}{133643}Please hold on!
{133658}{133708}He didn't run from piloting the Eva.
{133730}{133822}He chose not to step down of his own|volition. We should entrust this to him!
{133858}{133910}Shinji, we're counting on you!
{133910}{133957}Ikari, do your best!
{134387}{134448}Please have some faith in your own son.
{134642}{134702}I will place my faith in him as well.
{134790}{134851}I'll leave it to you. Do as you please.
{134852}{134884}Thank you, sir!
{134912}{134936}Shinji-kun.
{134943}{134968}Yes...?
{134973}{135042}We're going to entrust you|with all of Japan's energy...
{135059}{135141}With our future... All humanity's future...
{135141}{135201}The future of all living|things that have survived...
{135216}{135254}They're all in your hands.
{135269}{135301}Try your hardest!
{135315}{135340}Yes!
{135396}{135428}Cannon locked into position.
{135428}{135464}Readjusting power discharge system.
{135464}{135512}Unit 01's G-type equipment has been purged.
{135519}{135597}Switching final firing|system to manual mode.
{135779}{135841}Enemy drill tip has breached|the ceiling directly above HQ!
{135845}{135874}Ready second shot!
{135924}{135983}Replacing fuse! Barrel cooling complete!
{135988}{136051}Power supply system is|operating at full capacity.
{136051}{136111}Ground crew evacuation complete.
{136111}{136158}No problems with any of|the discharge plugs.
{136158}{136220}Final sniping specifications|data entry complete.
{136220}{136298}Any further adjustments will have|to be done manually, by the pilot!
{136298}{136358}We'll reach discharge pressure in 0.2!
{136391}{136442}High-order energy readings|from target again!
{136449}{136474}Crap!
{136682}{136707}Shinji-kun!
{137010}{137036}Ayanami!
{137168}{137192}The shield won't hold!
{137192}{137210}How much longer?!
{137214}{137238}Only 20 seconds!
{137257}{137282}Hurry...
{137480}{137527}Come on... Come on!
{137603}{137628}Come on!
{138425}{138450}We did it!
{139218}{139243}Ayanami!
{139365}{139400}Ayanami!
{140214}{140247}Ayanami!
{140250}{140270}Are you okay?!
{140270}{140308}Ayanami?! Ayanami!
{140585}{140689}Don't say things like,|"I have nothing else".
{140760}{140872}Don't say sad things like "farewell,"|as if we'll never meet again...
{141110}{141151}Why are you crying?
{141231}{141259}I'm sorry.
{141268}{141358}I don't know what kind of expression|I should have at a time like this...
{141392}{141443}It'd be best if you smiled, I think.
{142387}{142551}Let me guess... The boy has awakened. Now we|enter the general phase of the plan, yes?
{142574}{142694}That's correct. The Dead Sea Scroll Apocrypha|have been fulfilled up to the Books of law.
{142707}{142764}The promised time draws near.
{142865}{142917}Not the Third again...
{142918}{142963}You never change, do you?
{142996}{143090}I look forward to meeting|you, Ikari Shinji-kun.
{143091}{143159}TO BE CONTINUED
{143331}{143428}It's only love
{143435}{143531}It's only love
{143578}{143778}If I can be granted just one wish,
{143786}{143986}then let me sleep by your|side, wherever that may be.
{143996}{144072}Beautiful world
{144072}{144202}Without regrets, my eyes are only on you.
{144204}{144276}Beautiful boy
{144281}{144476}You don't know yet, just|how beautiful you are.
{144479}{144562}It's only love
{144620}{144766}Whether you're sleeping or awake,
{144770}{144970}You just dream of shounen manga, silly.|Don't you like yourself?
{145036}{145186}You don't know what you want,|but you can't stop wanting.
{145189}{145389}Lukewarm tears roll down your cheeks.
{145456}{145507}I have nothing I want to tell you,
{145509}{145606}I just want to meet you again.
{145662}{145710}I can't say what I want to tell you,
{145716}{145815}Maybe I'm just a coward.
{145826}{145874}But that's all right too.
{145874}{146074}If I can be granted just one wish,
{146082}{146282}Please let me sleep next to you.|Wherever that may be.
{146291}{146366}Beautiful world
{146366}{146499}Without regrets, my eyes are only on you.
{146499}{146572}Beautiful boy
{146576}{146754}You don't know yet, just|how beautiful you are.
{146774}{146859}It's only love
{146915}{147067}No matter what it is,|give everything a try.
{147068}{147268}Even if you get hurt, it's|a valuable experience.
{147332}{147384}I don't see the need for newspapers,
{147387}{147460}The important things are not printed there.
{147541}{147589}How are you doing recently?
{147596}{147667}So long as you are well,
{147705}{147752}I'll be fine.
{147752}{147952}If I can't meet you before my world ends,
{147961}{148161}Please let me sleep next to you.|Wherever that may be.
{148169}{148245}Beautiful world
{148245}{148377}As these fleeting days pass by,
{148377}{148454}Beautiful boy
{148456}{148579}It's natural to feel whimsical.
{148586}{148786}If I can be granted just one wish,
{148796}{148972}Please let me sleep next to you.
{149422}{149500}Beautiful world
{149628}{149702}Beautiful boy
{149838}{149914}Beautiful world
{150047}{150120}Beautiful boy
{150256}{150332}Beautiful world
{150672}{150690}PREVIEW
{150691}{150740}Backup Eva 05 is sortied into action.
{150740}{150795}Unit 02 and its pilot are|moved to the front lines.
{150804}{150844}Unit 04 mysteriously goes missing.
{150856}{150912}The disaster that took place when|Unit 03 was forcefully activated.
{150923}{151006}And finally, Unit 06 and its|pilot descend from the moon!
{151031}{151150}As Ikari Shinji continues to mentally|deteriorate, where will our story lead?
{151170}{151254}Next time in Rebuild of|Evangelion 2.0: Division
{151269}{151350}And we'll have lots of|fan service for you next time, too!
